apiVersion: v1
kind: Pod
metadata:
  name: online-inference-1
  labels:
    app: online-inference-1
spec:
  containers:
    - image: chydlife/online_inference:v2
      name: online-inference-1
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"